---
title: "2024年心理学統計法　中間試験（計70点）"
css: my.css
output:
  html_document: default
  word_document: default
---
## 注意点
回答すべき数値に小数点以下の桁が生じて問題文では桁数が指定されていない場合は小数点以下第2位までを答えること。ただし問題文で桁数が指定されている場合は、それに従うこと。どちらの場合も、指定された桁数の下一桁を四捨五入して丸めることとする。

## 1
以下の文章を読み、内容に誤りがない場合は解答欄に〇を、誤りがあると考えた場合には、そう考えた理由を簡潔に記せ。誤りがある場合には×と書くのではなく、理由を書くことに注意すること。（各3点；計24点）
)

1. 記述統計と推測統計は役割が異なるため、1つの研究データに対して両方を実施することはない。
2. 連続量のデータを要約する場合、基本的には中央値を算出するが、外れ値の影響を避けたい場合などに平均値を用いる場合もある。
3. 分散は、偏差の二乗和の平均値のことである。
4. 連続量として取得されたデータを使ってヒストグラムを作成すればデータについての情報は十分に得られるので、平均や標準偏差を算出する必要はない。
5. xをカテゴリ、yを累積度数として累積度数表を作成すると、表の最後の列のyの値は、データの大きさ（データ数）と必ず等しくなる。
6. 相関係数算出と線形回帰は、どちらも2変数間の関係を示すための方法なので、どちらかだけを実施すれば十分である。
7. 推測統計とは、標本として得たデータに欠損値があった場合に、その値を推測するための手続きである。
8. この科目で学ぶ推測統計は、データの母集団が正規分布するという前提に基づいて行われる。

## 2
標本データとして「7, 6, 8, 10, 6, 5, 7」という7つの数値が得られた。このデータを用いて、以下の問いに答えよ。（計13点）

1. 与えられたデータの平均を計算する式を書け。平均値そのものではなく、式を書くということに注意すること。具体的に数値を入れた式を書くこと（例えば、1と2の和を求める式の場合、1+2 のように答えれば良い）。（3点）
2. 与えられたデータの標準偏差を求める式を書け。ただし、標本分散をもとに算出する方の標準偏差とする。標本分散($s^2$)を求めるための式は一般的に下記のように与えられる。この問いも、具体的に数値を示した式を書かなくてはいけない。式の中で必要な値（例えば平均値や中央値など）は、あらかじめ算出しておき、その値を式の中で使うこと（小数点以下の桁数が生じた場合は小数点以下第2位まで記す）。あらかじめ値を算出する際はソフトウェアを用いても良い。この問題では標準偏差自体を求めるソフトウェアの関数を使用することは認めない。（5点）

  - $s^2=\frac{\sum^{n}_{i=1}(x_i-\bar{x})^2}{n}$

3. 与えられた標本データをもとに不偏分散を算出し、値を小数点以下第2位まで記せ。算出にはソフトウェアの使用など、どのような方法を使っても良いが、必ずどの方法を使って算出したかも記すこと。ソフトウェアを使用した場合は、使用したソフトと使用した関数および実行内容も明記する。算出方法の記述も採点対象とし、値が間違っていても部分点を与える場合がある。（5点）

## 3
eシラバスから2024middata1.csvを入手し、データxとデータyについて以下の問いに答えよ。計算にはソフトウェアを用いても良い。（計20点）

1. データx, データy、それぞれについて書いたヒストグラムをもとに、それぞれの分布の特徴を簡潔に述べよ。ヒストグラムを提出する必要はない。（各2点）
2. データxとデータyの散布図をもとに、xとyの間の関係について簡潔に述べよ。散布図を提出する必要はない。（3点）
3. xとyの相関係数を算出し、小数点以下第3位まで記せ。（2点）
4. yをxで直線回帰したとき、$\tilde{y}=a+bx$の切片aと回帰係数bを求め、記せ。（各2点）
5. 問4の直線回帰をした際のデータとの当てはまり具合（$R^2$）を算出し、小数点以下第2位まで記せ。（3点）
6. 問3から問5の結果から考えると、データxとデータyの関係はどのようなものか。文章で表せ。（4点）

## 4
eシラバスから2024middata2.csvを入手し、データzについて以下の問いに答えよ。（計13点）

1. データの大きさ（データ数）はいくつか。（2点）
2. データzがある母集団から抽出した標本であるとき、標本平均はいくつか。小数点以下第2位まで記せ。この問いはどのような方法で算出しても良い。（2点）
3. データzから不偏分散にもとづく標準偏差を算出し、小数点以下第2位まで記せ。この問いはどのような方法で算出しても良い。（3点）
4. データzをもとに、母平均の95%信頼区間を求め、その上限と下限を小数点以下第2位まで記せ。ただし、算出に使用する値は途中で丸めずに使用しないと解答の値が正解とずれてしまうので注意すること。（各3点）
